import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Helper to format dates
const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  const d = new Date(dateString);
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
};

// Colors matching the UI theme
const colors = {
  primary: [15, 23, 42], // slate-900
  secondary: [100, 116, 139], // slate-500
  accent: [59, 130, 246], // blue-500
  normal: [34, 197, 94], // green-500
  attention: [249, 115, 22], // orange-500
  critical: [239, 68, 68], // red-500
  bgLight: [248, 250, 252], // slate-50
  border: [226, 232, 240] // slate-200
};

export const generateReportPDF = async (report, user) => {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 15;
    let cursorY = margin;

    // --- HELPER: Add Footer to all pages ---
    const addFooters = () => {
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        
        // Footer Line
        doc.setDrawColor(...colors.border);
        doc.line(margin, pageHeight - 20, pageWidth - margin, pageHeight - 20);
        
        // Disclaimer
        doc.setFontSize(7);
        doc.setTextColor(...colors.secondary);
        doc.setFont('helvetica', 'italic');
        const disclaimer = "This interpretation is for educational purposes only and is not a medical diagnosis, prescription, or treatment plan. Please consult a qualified healthcare professional for medical advice.";
        const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - margin * 2);
        doc.text(splitDisclaimer, margin, pageHeight - 15);
        
        // Page Info
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.text(`MedScanAI | Generated by Gemini 2.5 Flash`, margin, pageHeight - 7);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 15, pageHeight - 7);
      }
    };

    // --- HEADER: Professional Cover Section ---
    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.setTextColor(...colors.primary);
    doc.text('MedScanAI', margin, cursorY + 8);
    
    // Subtitle
    doc.setFontSize(14);
    doc.setTextColor(...colors.accent);
    const reportType = report.reportType ? report.reportType.charAt(0).toUpperCase() + report.reportType.slice(1) : 'Medical';
    doc.text(`${reportType} Report Analysis`, margin, cursorY + 16);

    // Right Side Header (Metadata)
    doc.setFontSize(9);
    doc.setTextColor(...colors.secondary);
    doc.setFont('helvetica', 'normal');
    doc.text(`Report ID: ${report._id?.slice(-8).toUpperCase() || 'N/A'}`, pageWidth - margin, cursorY + 8, { align: 'right' });
    doc.text(`Generated: ${formatDate(new Date())}`, pageWidth - margin, cursorY + 12, { align: 'right' });
    doc.text(`Lab Date: ${formatDate(report.reportDate)}`, pageWidth - margin, cursorY + 16, { align: 'right' });

    // Divider
    cursorY += 22;
    doc.setDrawColor(...colors.border);
    doc.setLineWidth(0.5);
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 8;

    // --- PATIENT INFO & HEALTH SCORE SECTION ---
    const patientName = report.familyMemberName === 'Self' ? (user?.name || 'Patient') : (report.familyMemberName || 'Patient');
    const abnormalValues = report.labValues?.filter(v => v.status !== 'normal') || [];
    const normalValues = report.labValues?.filter(v => v.status === 'normal') || [];
    
    // Patient Info Block
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.primary);
    doc.text(`Patient Name: `, margin, cursorY);
    doc.setFont('helvetica', 'normal');
    doc.text(patientName, margin + 25, cursorY);
    
    doc.setFont('helvetica', 'bold');
    doc.text(`Lab Facility: `, margin, cursorY + 6);
    doc.setFont('helvetica', 'normal');
    doc.text(report.labName || 'Unknown', margin + 22, cursorY + 6);

    // Health Score Block (Right aligned)
    let badgeColor = colors.normal;
    let badgeText = 'NORMAL';
    if (report.overallStatus === 'urgent') {
      badgeColor = colors.critical;
      badgeText = 'URGENT';
    } else if (report.overallStatus === 'attention') {
      badgeColor = colors.attention;
      badgeText = 'ATTENTION';
    }

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.primary);
    doc.text(`Overall Status:`, pageWidth - margin - 45, cursorY);
    doc.setTextColor(...badgeColor);
    doc.text(badgeText, pageWidth - margin - 15, cursorY);

    doc.setTextColor(...colors.secondary);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Metrics: ${report.labValues?.length || 0}`, pageWidth - margin - 45, cursorY + 6);
    doc.text(`Normal: ${normalValues.length}`, pageWidth - margin - 45, cursorY + 11);
    doc.text(`Abnormal: ${abnormalValues.length}`, pageWidth - margin - 45, cursorY + 16);

    cursorY += 25;

    // --- LAB RESULTS TABLE ---
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.primary);
    doc.text('Detailed Lab Results', margin, cursorY);
    cursorY += 5;

    const tableData = (report.labValues || []).map(val => [
      val.name || '-',
      val.value !== undefined ? String(val.value) : '-',
      val.unit || '-',
      (val.referenceMin !== undefined && val.referenceMax !== undefined) ? `${val.referenceMin} - ${val.referenceMax}` : '-',
      val.status ? val.status.toUpperCase() : '-',
      val.explanation || '-'
    ]);

    doc.autoTable({
      startY: cursorY,
      head: [['Parameter', 'Value', 'Unit', 'Ref. Range', 'Status', 'Explanation']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: colors.primary,
        textColor: [255, 255, 255],
        fontSize: 9,
        fontStyle: 'bold'
      },
      styles: {
        fontSize: 8,
        cellPadding: 4,
        textColor: colors.primary
      },
      columnStyles: {
        0: { cellWidth: 35, fontStyle: 'bold' },
        1: { cellWidth: 15 },
        2: { cellWidth: 15 },
        3: { cellWidth: 25 },
        4: { cellWidth: 20, fontStyle: 'bold' },
        5: { cellWidth: 'auto' } // Explanation takes remaining space
      },
      didParseCell: function(data) {
        // Color code the Status column
        if (data.section === 'body' && data.column.index === 4) {
          const status = data.cell.raw;
          if (status === 'CRITICAL' || status === 'HIGH') {
            data.cell.styles.textColor = colors.critical;
          } else if (status === 'BORDERLINE' || status === 'LOW') {
            data.cell.styles.textColor = colors.attention;
          } else if (status === 'NORMAL') {
            data.cell.styles.textColor = colors.normal;
          }
        }
      },
      margin: { top: margin, right: margin, bottom: 25, left: margin }
    });

    cursorY = doc.lastAutoTable.finalY + 15;

    // Helper function to check page break
    const checkPageBreak = (neededSpace) => {
      if (cursorY + neededSpace > pageHeight - 25) {
        doc.addPage();
        cursorY = margin;
      }
    };

    // --- AI SUMMARY ---
    if (report.summary) {
      checkPageBreak(40);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.primary);
      doc.text('AI Summary Analysis', margin, cursorY);
      cursorY += 6;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...colors.secondary);
      const splitSummary = doc.splitTextToSize(report.summary, pageWidth - margin * 2);
      doc.text(splitSummary, margin, cursorY);
      cursorY += (splitSummary.length * 5) + 10;
    }

    // --- CLINICAL GUIDANCE ---
    if (report.clinicalGuidance) {
      const cg = report.clinicalGuidance;
      checkPageBreak(60);
      
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colors.primary);
      doc.text('Clinical Guidance', margin, cursorY);
      cursorY += 8;

      // Specialist & Urgency
      if (cg.specialistType || cg.urgencyLevel) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        if (cg.specialistType) {
          doc.text(`Recommended Specialist: ${cg.specialistType}`, margin, cursorY);
        }
        if (cg.urgencyLevel) {
          doc.text(`Urgency Level: ${cg.urgencyLevel.toUpperCase()}`, margin + 90, cursorY);
        }
        cursorY += 8;
      }

      // Concerns
      if (cg.concerns && cg.concerns.length > 0) {
        checkPageBreak(30);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...colors.attention);
        doc.text('Possible Health Concerns:', margin, cursorY);
        cursorY += 6;

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...colors.primary);
        cg.concerns.forEach(concern => {
          const split = doc.splitTextToSize(`• ${concern}`, pageWidth - margin * 2 - 5);
          checkPageBreak(split.length * 5 + 5);
          doc.text(split, margin + 5, cursorY);
          cursorY += split.length * 5;
        });
        cursorY += 5;
      }

      // Next Steps
      if (cg.nextSteps && cg.nextSteps.length > 0) {
        checkPageBreak(30);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...colors.accent);
        doc.text('Recommended Next Steps:', margin, cursorY);
        cursorY += 6;

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...colors.primary);
        cg.nextSteps.forEach(step => {
          const split = doc.splitTextToSize(`• ${step}`, pageWidth - margin * 2 - 5);
          checkPageBreak(split.length * 5 + 5);
          doc.text(split, margin + 5, cursorY);
          cursorY += split.length * 5;
        });
        cursorY += 5;
      }
    }

    // Add footers across all generated pages
    addFooters();

    // Construct File Name
    const sanitizedName = patientName.replace(/[^a-zA-Z0-9]/g, '_');
    const dateStr = new Date().toISOString().split('T')[0];
    const fileName = `MedScanAI_Report_${sanitizedName}_${dateStr}.pdf`;

    // Download the PDF
    doc.save(fileName);
    return true;
  } catch (error) {
    console.error('PDF Generation failed:', error);
    throw error;
  }
};
